# Tables
[table-1]
key1 = "some string"
key2 = 123

[table-2]
key1 = "another string"
key2 = 456

# Nested tables
[dog."tater.man"]
type.name = "pug"

# Inline tables
name = { first = "Tom", last = "Preston-Werner" }
point = { x = 1, y = 2 }
animal = { type.name = "pug" }

# Array of tables
[[products]]
name = "Hammer"
sku = 738594937

[[products]]  # empty table

[[products]]
name = "Nail"
sku = 284758393
color = "gray"

# Nested array of tables
[[fruits]]
name = "apple"

[fruits.physical]
color = "red"
shape = "round"

[[fruits.varieties]]
name = "red delicious"

[[fruits.varieties]]
name = "granny smith"

[[fruits]]
name = "banana"

[[fruits.varieties]]
name = "plantain"
